-- EXTERNAL TABLE: studient.nwea_reports
-- Extracted from AWS Athena on 2026-03-29

CREATE EXTERNAL TABLE `studient.nwea_reports`(
  `termname` string COMMENT 'from deserializer', 
  `districtname` string COMMENT 'from deserializer', 
  `district_stateid` string COMMENT 'from deserializer', 
  `schoolname` string COMMENT 'from deserializer', 
  `school_stateid` string COMMENT 'from deserializer', 
  `studentid` string COMMENT 'from deserializer', 
  `student_stateid` string COMMENT 'from deserializer', 
  `subject` string COMMENT 'from deserializer', 
  `course` string COMMENT 'from deserializer', 
  `growthmeasureyn` string COMMENT 'from deserializer', 
  `normsreferencedata` string COMMENT 'from deserializer', 
  `wiselectedayfall` string COMMENT 'from deserializer', 
  `wiselectedaywinter` string COMMENT 'from deserializer', 
  `wiselectedayspring` string COMMENT 'from deserializer', 
  `wipreviousayfall` string COMMENT 'from deserializer', 
  `wipreviousaywinter` string COMMENT 'from deserializer', 
  `wipreviousayspring` string COMMENT 'from deserializer', 
  `testtype` string COMMENT 'from deserializer', 
  `testname` string COMMENT 'from deserializer', 
  `testid` string COMMENT 'from deserializer', 
  `teststartdate` string COMMENT 'from deserializer', 
  `teststarttime` string COMMENT 'from deserializer', 
  `testdurationminutes` string COMMENT 'from deserializer', 
  `testritscore` string COMMENT 'from deserializer', 
  `teststandarderror` string COMMENT 'from deserializer', 
  `testpercentile` string COMMENT 'from deserializer', 
  `achievementquintile` string COMMENT 'from deserializer', 
  `percentcorrect` string COMMENT 'from deserializer', 
  `rapidguessingpercentage` string COMMENT 'from deserializer', 
  `falltofallprojectedgrowth` string COMMENT 'from deserializer', 
  `falltofallobservedgrowth` string COMMENT 'from deserializer', 
  `falltofallobservedgrowthse` string COMMENT 'from deserializer', 
  `falltofallmetprojectedgrowth` string COMMENT 'from deserializer', 
  `falltofallconditionalgrowthindex` string COMMENT 'from deserializer', 
  `falltofallconditionalgrowthpercentile` string COMMENT 'from deserializer', 
  `falltofallgrowthquintile` string COMMENT 'from deserializer', 
  `falltowinterprojectedgrowth` string COMMENT 'from deserializer', 
  `falltowinterobservedgrowth` string COMMENT 'from deserializer', 
  `falltowinterobservedgrowthse` string COMMENT 'from deserializer', 
  `falltowintermetprojectedgrowth` string COMMENT 'from deserializer', 
  `falltowinterconditionalgrowthindex` string COMMENT 'from deserializer', 
  `falltowinterconditionalgrowthpercentile` string COMMENT 'from deserializer', 
  `falltowintergrowthquintile` string COMMENT 'from deserializer', 
  `falltospringprojectedgrowth` string COMMENT 'from deserializer', 
  `falltospringobservedgrowth` string COMMENT 'from deserializer', 
  `falltospringobservedgrowthse` string COMMENT 'from deserializer', 
  `falltospringmetprojectedgrowth` string COMMENT 'from deserializer', 
  `falltospringconditionalgrowthindex` string COMMENT 'from deserializer', 
  `falltospringconditionalgrowthpercentile` string COMMENT 'from deserializer', 
  `falltospringgrowthquintile` string COMMENT 'from deserializer', 
  `wintertowinterprojectedgrowth` string COMMENT 'from deserializer', 
  `wintertowinterobservedgrowth` string COMMENT 'from deserializer', 
  `wintertowinterobservedgrowthse` string COMMENT 'from deserializer', 
  `wintertowintermetprojectedgrowth` string COMMENT 'from deserializer', 
  `wintertowinterconditionalgrowthindex` string COMMENT 'from deserializer', 
  `wintertowinterconditionalgrowthpercentile` string COMMENT 'from deserializer', 
  `wintertowintergrowthquintile` string COMMENT 'from deserializer', 
  `wintertospringprojectedgrowth` string COMMENT 'from deserializer', 
  `wintertospringobservedgrowth` string COMMENT 'from deserializer', 
  `wintertospringobservedgrowthse` string COMMENT 'from deserializer', 
  `wintertospringmetprojectedgrowth` string COMMENT 'from deserializer', 
  `wintertospringconditionalgrowthindex` string COMMENT 'from deserializer', 
  `wintertospringconditionalgrowthpercentile` string COMMENT 'from deserializer', 
  `wintertospringgrowthquintile` string COMMENT 'from deserializer', 
  `springtospringprojectedgrowth` string COMMENT 'from deserializer', 
  `springtospringobservedgrowth` string COMMENT 'from deserializer', 
  `springtospringobservedgrowthse` string COMMENT 'from deserializer', 
  `springtospringmetprojectedgrowth` string COMMENT 'from deserializer', 
  `springtospringconditionalgrowthindex` string COMMENT 'from deserializer', 
  `springtospringconditionalgrowthpercentile` string COMMENT 'from deserializer', 
  `springtospringgrowthquintile` string COMMENT 'from deserializer', 
  `lexilescore` string COMMENT 'from deserializer', 
  `lexilemin` string COMMENT 'from deserializer', 
  `lexilemax` string COMMENT 'from deserializer', 
  `quantilescore` string COMMENT 'from deserializer', 
  `quantilemin` string COMMENT 'from deserializer', 
  `quantilemax` string COMMENT 'from deserializer', 
  `goal1name` string COMMENT 'from deserializer', 
  `goal1ritscore` string COMMENT 'from deserializer', 
  `goal1stderr` string COMMENT 'from deserializer', 
  `goal1range` string COMMENT 'from deserializer', 
  `goal1adjective` string COMMENT 'from deserializer', 
  `goal2name` string COMMENT 'from deserializer', 
  `goal2ritscore` string COMMENT 'from deserializer', 
  `goal2stderr` string COMMENT 'from deserializer', 
  `goal2range` string COMMENT 'from deserializer', 
  `goal2adjective` string COMMENT 'from deserializer', 
  `goal3name` string COMMENT 'from deserializer', 
  `goal3ritscore` string COMMENT 'from deserializer', 
  `goal3stderr` string COMMENT 'from deserializer', 
  `goal3range` string COMMENT 'from deserializer', 
  `goal3adjective` string COMMENT 'from deserializer', 
  `goal4name` string COMMENT 'from deserializer', 
  `goal4ritscore` string COMMENT 'from deserializer', 
  `goal4stderr` string COMMENT 'from deserializer', 
  `goal4range` string COMMENT 'from deserializer', 
  `goal4adjective` string COMMENT 'from deserializer', 
  `goal5name` string COMMENT 'from deserializer', 
  `goal5ritscore` string COMMENT 'from deserializer', 
  `goal5stderr` string COMMENT 'from deserializer', 
  `goal5range` string COMMENT 'from deserializer', 
  `goal5adjective` string COMMENT 'from deserializer', 
  `goal6name` string COMMENT 'from deserializer', 
  `goal6ritscore` string COMMENT 'from deserializer', 
  `goal6stderr` string COMMENT 'from deserializer', 
  `goal6range` string COMMENT 'from deserializer', 
  `goal6adjective` string COMMENT 'from deserializer', 
  `goal7name` string COMMENT 'from deserializer', 
  `goal7ritscore` string COMMENT 'from deserializer', 
  `goal7stderr` string COMMENT 'from deserializer', 
  `goal7range` string COMMENT 'from deserializer', 
  `goal7adjective` string COMMENT 'from deserializer', 
  `goal8name` string COMMENT 'from deserializer', 
  `goal8ritscore` string COMMENT 'from deserializer', 
  `goal8stderr` string COMMENT 'from deserializer', 
  `goal8range` string COMMENT 'from deserializer', 
  `goal8adjective` string COMMENT 'from deserializer', 
  `typicalfalltofallgrowth` string COMMENT 'from deserializer', 
  `typicalfalltowintergrowth` string COMMENT 'from deserializer', 
  `typicalfalltospringgrowth` string COMMENT 'from deserializer', 
  `typicalwintertowintergrowth` string COMMENT 'from deserializer', 
  `typicalwintertospringgrowth` string COMMENT 'from deserializer', 
  `typicalspringtospringgrowth` string COMMENT 'from deserializer', 
  `projectedproficiencystudy1` string COMMENT 'from deserializer', 
  `projectedproficiencylevel1` string COMMENT 'from deserializer', 
  `projectedproficiencystudy2` string COMMENT 'from deserializer', 
  `projectedproficiencylevel2` string COMMENT 'from deserializer', 
  `projectedproficiencystudy3` string COMMENT 'from deserializer', 
  `projectedproficiencylevel3` string COMMENT 'from deserializer', 
  `projectedproficiencystudy4` string COMMENT 'from deserializer', 
  `projectedproficiencylevel4` string COMMENT 'from deserializer', 
  `projectedproficiencystudy5` string COMMENT 'from deserializer', 
  `projectedproficiencylevel5` string COMMENT 'from deserializer', 
  `projectedproficiencystudy6` string COMMENT 'from deserializer', 
  `projectedproficiencylevel6` string COMMENT 'from deserializer', 
  `projectedproficiencystudy7` string COMMENT 'from deserializer', 
  `projectedproficiencylevel7` string COMMENT 'from deserializer', 
  `projectedproficiencystudy8` string COMMENT 'from deserializer', 
  `projectedproficiencylevel8` string COMMENT 'from deserializer', 
  `projectedproficiencystudy9` string COMMENT 'from deserializer', 
  `projectedproficiencylevel9` string COMMENT 'from deserializer', 
  `projectedproficiencystudy10` string COMMENT 'from deserializer', 
  `projectedproficiencylevel10` string COMMENT 'from deserializer', 
  `classname` string COMMENT 'from deserializer', 
  `teachername` string COMMENT 'from deserializer', 
  `teacherid` string COMMENT 'from deserializer', 
  `teacher_stateid` string COMMENT 'from deserializer', 
  `studentlastname` string COMMENT 'from deserializer', 
  `studentfirstname` string COMMENT 'from deserializer', 
  `studentmi` string COMMENT 'from deserializer', 
  `studentdateofbirth` string COMMENT 'from deserializer', 
  `studentethnicgroup` string COMMENT 'from deserializer', 
  `nweastandard_ethnicgroup` string COMMENT 'from deserializer', 
  `studentgender` string COMMENT 'from deserializer', 
  `grade` string COMMENT 'from deserializer', 
  `nweastandard_grade` string COMMENT 'from deserializer', 
  `learningrate` string COMMENT 'from deserializer', 
  `termprojectedgrowth` string COMMENT 'from deserializer', 
  `termobservedgrowth` string COMMENT 'from deserializer', 
  `teststartdatelatestinterm` string COMMENT 'from deserializer', 
  `minstandarderror` string COMMENT 'from deserializer')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'escapeChar'='\\', 
  'quoteChar'='\"', 
  'separatorChar'=',') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://alpha-backend-prod-progressrecordstore-1n0x2ke8vjgjr/nwea_reports'
TBLPROPERTIES (
  'skip.header.line.count'='1', 
  'transient_lastDdlTime'='1772770914')
